name: Whisky University
favicon: null
layout_spectrum: 0.7072969775181264
typography_spectrum: 0.5529592158272862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21598322479985654
  lightness: 0.6269897057209164
  saturation: 0.9323145502712578
  rhythmicContrast: 0.312204439425841
purpose: []
