name: Whisky University
favicon: null
layout_spectrum: 0.87058
typography_spectrum: 0.52474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#281413'
    - '#aac0ce'
    - '#5d7277'
    - '#bf8237'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
