name: Whisky University
favicon: null
layout_spectrum: 0.52009
typography_spectrum: 0.5529592158272862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8e3'
    - '#749ca4'
    - '#080000'
    - '#5d5a63'
    - '#532102'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
